[versions]
android-compileSdk = "36"
android-minSdk = "29"
android-targetSdk = "36"
androidx-activityCompose = "1.12.2"
compose-plugin = "1.9.3"
kotlin = "2.3.0"
korender-version = "0.6.0"
androidx-lifecycle = "2.9.6"
kotlinx-coroutines-core-ver = "1.10.2"
kotlin-coroutines-okhttp-ver = "1.0"
simplifyK-ver = "0.2.0"
koinVersion = "4.1.1"
adaptive = "1.2.0"
material3Adaptive = "1.2.0"
colorpicker = "1.1.3"
compose-ui = "1.10.0"
androidGradlePlugin = "8.13.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
korender = { module = "com.github.zakgof:korender", version.ref = "korender-version" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core-ver" }
kotlin-coroutines-okhttp = { module = "ru.gildor.coroutines:kotlin-coroutines-okhttp", version.ref = "kotlin-coroutines-okhttp-ver" }
simplifyK = { module = "dev.jamesyox:simplifyK", version.ref = "simplifyK-ver" }
koin = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinVersion" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koinVersion" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koinVersion" }
#androidx-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }
compose-colorpicker = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker" }
#androidx-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "material3Adaptive" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }